### ISSUE TITLE
lets encrypt SSL

### ISSUE THREAD

**Issue by digcatcom** [aborroy/alfresco-docker-installer#1]
Hi Angel
Love your work !,  It would be awesome to also have a letsencrypt ssl out the box, then the mobile app could be tested against the install.  Maybe integrate your ssl-base project?
Daren

**Comment by aborroy** [comment]
Using Let's Encrypt implies the server to be available in Internet. Probably it's better to leave the users to configure that outside Docker if required.

**Comment by digcatcom** [comment]
yes it does imply the server is online, but it needs an ssl for the mobile client to work so it would be a good feature as a choice, like ldap etc.  perhaps its something for a pull request in the future.
